server:
  port: 8080
  contextPath: /fct
  tomcat:
    uri-encoding: UTF-8

redis:
  host:
    url: redis.fct.me
    port: 9005
    test:
      onborrow: true
    max:
      idel: 300
      total: 300
      waitmillis: 1000

mongo:
  host:
    port: 9023
    url: mongo-m.fct.me
    db: easemob
    collectionName: sms_log

mysql:
  connection:
    url: jdbc:mysql://localhost:3006/fct_core?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: admin
    password: admin



