server:
  port: 8080
  contextPath: /fct
  tomcat:
    uri-encoding: UTF-8

redis:
  host:
    url: redis1-pe1.fct.me
    port: 9001
    test:
      onborrow: true
    password: admin
    max:
      idel: 300
      total: 300
      waitmillis: 1000

mongo:
  host:
    port: 9023
    url: mongo1-pe1.fct.me
    db: message
    collectionName: sms_log
    username: admin
    password: admin

mysql:
  connection:
    url: jdbc:mysql://localhost:3006/fct_core?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: admin
    password: admin
